server.port: 31212
logging.pattern.console: '%d{yyyy-MM-dd HH:mm:ss} [%5p] %m%n'
spring.config.location: application.yaml

logging:
  level:
    root: info


tunnel:
  username: lilongtao
  password: xxx
  tunnels:
    - port: 8888
      resource: git
      server: ${server.mvp}
    - port: 3306
      resource: mvpmysql
      server: ${server.mvp}
    - port: 13306
      resource: premysql
      server: ${server.pre}
    - port: 2122
      resource: pressh
      server: ${server.pre}


