logging.pattern.console: '%d{yyyy-MM-dd HH:mm:ss} [%5p] %m%n'

logging:
  level:
    root: info

#tunnel:
#  username: 你的用户名
#  password: 你的密码
#  tunnels:
#    - port: 3001
#      resource: test
#      server: ws://你的服务器地址/message
#    - port: 3002
#      resource: test2
#      server: ws://你的服务器地址/message



